apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap-agent-config.yaml
  - pvc-agent-state.yaml
  - secret-alpaca-hackathon-agent-dev-sealed.yaml
  - secret-alpaca-hackathon-agent-contest-sealed.yaml
  - secret-harbor-push-auth-sealed.yaml
  - deployment-alpaca-hackathon-agent.yaml
