---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-push-auth
  namespace: alpaca-hackathon-agent
spec:
  encryptedData:
    .dockerconfigjson: AgAw9l7eeAH1fVxKJD6mbwEAxjUexrX6xSr30EdqVad0UtCUSCOaweH/yrLLZI41lPqBkph3d0+eKEywVVTt0mATBrQulr3B/MgVEW71Wpj5zoLWPXgz/f0gcBUgdY71uuhnlJ5CgT+FD8yuVjADm5lRvr+LYcv47B16oUSx+NU93JO2w/OaRjFOmsDidgLKO2RXkIGVkSNB3vuwqBOHbpYTpUfJT+BskmGpvX3oRT8P8Xywx/bWDuCqST+GUj/e7x3FTr1wVO4jmg2j2jUik6QEy0yRmHv912gvH4X0AEzt9EjoBLalVKIy0dJ6+j/dwTH8XceoKUZ6deT1GH3i1DpwpVMYsul4sSRXnd3GrOEuka/kb6p7OWwAlxVytDPRGXHC7qVsFCXdZpV20oivaosmPtkcjNDVcGjltehSOi+qaOUhROzp83zmZZxyHBvVSUFT4vlEMVtIYVnvQvtNRUWwuKdimVBS5OKt1K3ZXc07gc6YMby83HxfEOol+fOAYzu/uHEKwmioF1H8MvV602fjkQmz+hNX6JRYKpMy/nPVj22KiIALXy/CVO3eHIe6o/oCCyUpJODB9qjBkjpNbKxoFsUei8EAcKbkKRXHsfjjr5hYwMBu/dvxBDHpnt2B47PGGc3mIG6NwYhud1vJiI+OcKxcAz6GdmDyMLFCh4cZ6CaWX/24eLQO7kpMuYZiYwG3+Q/8H+YIqnW6nXI9A1gLNdExrYRCbyFEQlyhmWZJtxzeewegYIGbYwV9OZWwuVHjJH82dhslzLP8V9q813STM48Il4+cKpXgbs6m4VZgaYJmFIeuZ8llrZXiIohkpdaTsR624N+zB8maHJR99pIitMYQK3Ua8T3jo7fIBd15mqOXkR4fmezk6SmlzEnzujG/DwFefYWAOv3KuLPCe7hW6Qun6jQLlsY2ExMrfwz+QfuDLAYj0T9nJ6ybZC/CcNq6YQQmRUpNWtf1jwqHBwq/+nk=
  template:
    metadata:
      name: harbor-push-auth
      namespace: alpaca-hackathon-agent
    type: kubernetes.io/dockerconfigjson
