apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap-muthur-status-web-static.yaml
  - secret-harbor-push-auth-sealed.yaml
  - secret-muthur-status-web-sealed.yaml
  - deployment-muthur-status-web.yaml
  - ingress-muthur-status-web-waf.yaml
